export const weatherData = [
  {
    title: "Влажность",
    icon: "/images/iconCards/humidity.svg",
    indication: "75",
    units: "%",
    minParams: "0",
    maxParams: "100",
  },
  {
    title: "Давление",
    pressure: true,
    icon: "/images/iconCards/barometr.svg",
    indication: "761",
    param: "Повышенное",
    minParams: "640",
    maxParams: "813",
  },
  {
    title: "Видимость",
    icon: "/images/iconCards/visibility.svg",
    indication: "28",
    units: "км",
    param: "Нормальная",
    minParams: "0",
    maxParams: "100",
  },
  {
    title: "Рассвет",
    icon: "/images/iconCards/sunrise.svg",
    currentTime: "8:42",
    param: "Прошло: ",
    time: "02:47",
  },
  {
    title: "Закат",
    icon: "/images/iconCards/sunset.svg",
    currentTime: "16:37",
    param: "Осталось: ",
    time: "05:08",
  },
  {
    title: "Сила ветра",
    icon: "/images/iconCards/iconsWind/direction.svg",
    windSpeed: "2 м/с",
    param: "Северо-западный",
  },
];
